[package]
name = "gotham-middleware-fs"
version = "0.1.0"
authors = ["Christoph Wurst <christoph@winzerhof-wurst.at>"]

[dependencies]
futures = "0.1"
futures-fs = "0.0.3"
gotham = "0.2"
gotham_derive = "0.2"

[dev-dependencies]
hyper = "*"
mime = "*"
